version: "3.4"

services:
  postgres:
    container_name: megaMart-db
    image: postgres
    ports:
      - 5434:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: megaMart
      POSTGRES_PASSWORD: megaMart 

volumes:
  postgres_data: